In [115]:
import numpy as np
import cv2

In [116]:
x=np.random.randn(5,1)+5
y=np.random.randn(5,1)+10
x,y

(array([[5.40801653],
        [4.65193149],
        [7.41167431],
        [4.16178089],
        [5.83474248]]),
 array([[10.4024917 ],
        [ 9.50494666],
        [10.97616656],
        [ 9.65437917],
        [10.45332725]]))

In [117]:
xf=np.floor(x)
yf=np.floor(y)
cornerx=np.array([0,0,1,1])
cornery=np.array([0,1,1,0])
idx=(xf+cornerx).astype(np.int32)
idy=(yf+cornery).astype(np.int32)
idy

array([[10, 11, 11, 10],
       [ 9, 10, 10,  9],
       [10, 11, 11, 10],
       [ 9, 10, 10,  9],
       [10, 11, 11, 10]], dtype=int32)

In [118]:
idx,idy

(array([[5, 5, 6, 6],
        [4, 4, 5, 5],
        [7, 7, 8, 8],
        [4, 4, 5, 5],
        [5, 5, 6, 6]], dtype=int32),
 array([[10, 11, 11, 10],
        [ 9, 10, 10,  9],
        [10, 11, 11, 10],
        [ 9, 10, 10,  9],
        [10, 11, 11, 10]], dtype=int32))

In [119]:
img=cv2.imread(r'imgs\sea.jpg')
points=img[idy,idx]

In [120]:
radio_x=1-(x-xf)
radio_y=1-(y-yf)
radio_x #(5,1)

array([[0.59198347],
       [0.34806851],
       [0.58832569],
       [0.83821911],
       [0.16525752]])

In [121]:
diffx=np.abs(radio_x-cornerx[None,:])
diffy=np.abs(radio_y-cornery[None,:])
raidx=(diffx*diffy)

In [122]:
(points*raidx[:,:,None]).sum(axis=1)

array([[ 40.7356181 ,  79.58902666,  56.2241719 ],
       [ 37.34004629,  59.32045117,  42.53051942],
       [ 51.54305201, 110.68642222,  79.38831373],
       [ 27.03934208,  47.7036727 ,  32.4580848 ],
       [ 44.54304721,  85.01244089,  59.80067229]])

In [123]:
points

array([[[ 28,  60,  41],
        [ 49,  96,  70],
        [ 35,  84,  56],
        [ 55,  89,  65]],

       [[ 42,  55,  41],
        [ 16,  39,  24],
        [ 28,  60,  41],
        [ 56,  72,  55]],

       [[ 46,  86,  61],
        [ 57, 114,  83],
        [ 44, 107,  75],
        [ 49, 103,  74]],

       [[ 42,  55,  41],
        [ 16,  39,  24],
        [ 28,  60,  41],
        [ 56,  72,  55]],

       [[ 28,  60,  41],
        [ 49,  96,  70],
        [ 35,  84,  56],
        [ 55,  89,  65]]], dtype=uint8)

In [125]:
def chazhi(point,img):

    x,y=point
    left=int(np.floor(x))
    right=int(np.ceil(x))
    up=int(np.floor(y))
    down=int(np.ceil(y))
    a=x-left
    b=y-up
    value=(1-a)*(1-b)*img[up,left]+a*(1-b)*img[up,right]+(1-a)*b*img[down,left]+a*b*img[down,right]

    return value

pt=[x[1],y[1]]
chazhi(pt,img)

C:\Users\sk759\AppData\Local\Temp\ipykernel_16744\3918668843.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  left=int(np.floor(x))
C:\Users\sk759\AppData\Local\Temp\ipykernel_16744\3918668843.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  right=int(np.ceil(x))
C:\Users\sk759\AppData\Local\Temp\ipykernel_16744\3918668843.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  up=int(np.floor(y))
C:\Users\sk759\AppData\Local\Temp\ipykernel_16744\3918668843.py:7:

array([37.34004629, 59.32045117, 42.53051942])

In [126]:
cc=np.random.rand(4,2)
np.split(cc,[1],axis=1,)

[array([[0.60475216],
        [0.37300728],
        [0.52546708],
        [0.30911209]]),
 array([[0.04365116],
        [0.45574506],
        [0.7335706 ],
        [0.70431486]])]