In [11]:
import numpy as np
np.set_printoptions(precision=3,suppress=True)

In [ ]:
points=np.random.randint(0,100,(200,2))
points=points+np.random.randn(200,2)
points

In [ ]:
xs,ys=np.split(points,[1],1)
xf=np.floor(xs)
yf=np.floor(ys)
cornerx=np.array([0,0,1,1])
cornery=np.array([0,1,1,0])

idx=(xf+cornerx).astype(np.int32)
idy=(yf+cornery).astype(np.int32)

idy

In [41]:
radiox=np.abs(xs-idx)
radiox[:,[0,1,2,3]]=radiox[:,[2,3,1,0]]
radioy=np.abs(ys-idy)
radioy[:,[0,1,2,3]]=radioy[:,[2,0,3,1]]
radioy

np.allclose(np.einsum('ij,ij->ij',radiox,radioy),radiox*radioy)

True

In [37]:
px=np.array([[1,2,3,4]])

data=np.arange(12).reshape(1,4,3)
data.shape,px.shape

((1, 4, 3), (1, 4))

In [34]:
res=(data*px[:,:,None])
res

array([[[ 0,  1,  2],
        [ 6,  8, 10],
        [18, 21, 24],
        [36, 40, 44]]])

In [35]:
res.sum(axis=1)

array([[60, 70, 80]])

In [39]:
np.einsum('ijk,ij->ik',data,px)

array([[60, 70, 80]])

In [42]:
p1=np.random.rand(100,2)
p2=np.random.rand(100,3)

np.tensordot(p2,p1,[0,0])

array([[25.411, 24.772],
       [25.489, 26.766],
       [24.63 , 25.176]])

In [59]:
np.einsum('ik,ij->kj',p2,p1)

array([[25.411, 24.772],
       [25.489, 26.766],
       [24.63 , 25.176]])

In [46]:
pcv=np.arange(25).reshape(5,5)
np.einsum('ii->',pcv)

np.int64(60)

In [55]:
a=np.random.rand(3)
b=np.random.rand(4)
np.einsum('i,j->ij',a,b)

array([[0.282, 0.053, 0.015, 0.094],
       [0.11 , 0.021, 0.006, 0.037],
       [0.375, 0.071, 0.02 , 0.126]])

In [54]:
s=0
for var in a:
    s+=(var*b).sum()
s

np.float64(3.3544877547434058)

In [50]:
b

array([0.433, 0.148, 0.51 , 0.882])