In [46]:
import numpy as np

In [47]:
data=np.random.randint(0,4,(10,2))
dx=np.random.randint(0,4,(5,2))
data,dx

(array([[1, 1],
        [0, 2],
        [3, 1],
        [0, 0],
        [2, 2],
        [3, 0],
        [2, 3],
        [3, 0],
        [3, 0],
        [0, 0]], dtype=int32),
 array([[3, 0],
        [1, 2],
        [3, 3],
        [2, 1],
        [2, 2]], dtype=int32))

In [49]:
data_x=data.view([('',data.dtype)]*data.shape[1])
dx_x=dx.view([('',dx.dtype)]*dx.shape[1])
np.setdiff1d(data_x,dx_x).view(data.dtype).reshape(-1,2)

array([[0, 0],
       [0, 2],
       [1, 1],
       [2, 3],
       [3, 1]], dtype=int32)

In [51]:
a=data.view([('',data.dtype)]*data.shape[1])
b=dx.view([('',dx.dtype)]*dx.shape[1])

np.setdiff1d(a,b).view(data.dtype).reshape(-1,2)

array([[0, 0],
       [0, 2],
       [1, 1],
       [2, 3],
       [3, 1]], dtype=int32)